[tool.bumpversion]
current_version = "1.0.0"
commit = false
allow_dirty = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "README.md"
search = "pre-commit-check-office-metadata/{current_version}"
replace = "pre-commit-check-office-metadata/{new_version}"

[[tool.bumpversion.files]]
filename = "README.md"
search = "rev: v{current_version}"
replace = "rev: v{new_version}"
