[tool.bumper]
current_version = "1.0.0"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./README.md"
search = "pre-commit-check-office-metadata/{current_version}"

[[tool.bumper.files]]
file = "./README.md"
search = "rev: v{current_version}"
