name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build dist & publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      run: curl -LsSf https://astral.sh/uv/0.4.30/install.sh | sh

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Build package
      run: uvx --from build pyproject-build --installer uv

    - name: Upload wheel to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release upload ${{ github.event.release.tag_name }} ./dist/pre_commit_check_office_metadata-*.whl
